[package]
name = "rust101"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.1"
colored = "2.1.0"
futures = { version = "0.3.30", features = ["thread-pool"] }


[[bin]]
name = "guessing_game"
path = "src/bin/guess_game.rs"
